theme: jekyll-theme-minimal
title: [fabriCELL]
description: [FABRICELL aims to support researchers exploring Chemistry-Biology space in the creative design of artificial cellular devices whereby living and non-living components are fused together using bottom-up approaches.]
